# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/btech/cs1160368/github/Col216_assignments/A6_ahb_lite_bus/lab6/lab6.cache/wt [current_project]
set_property parent.project_path /home/btech/cs1160368/github/Col216_assignments/A6_ahb_lite_bus/lab6/lab6.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/btech/cs1160368/github/Col216_assignments/A6_ahb_lite_bus/lab6/lab6.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /home/btech/cs1160368/github/Col216_assignments/A6_ahb_lite_bus/lab6/lab6.srcs/sources_1/imports/A6/decoder.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top decoder -part xc7a35tcpg236-1


write_checkpoint -force -noxdef decoder.dcp

catch { report_utilization -file decoder_utilization_synth.rpt -pb decoder_utilization_synth.pb }
