webtalk_init -webtalk_dir /media/root/New Volume/IITD/4th/COL 216/Lab/A5/DataPath/DataPath.sim/sim_1/behav/xsim.dir/DC_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Apr 12 00:06:07 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1756540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5b8e2c69-a7f8-4882-a9c3-413537382d5c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e511bf369e25450ab78ca9f7c5b280e8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Kali" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Kali GNU/Linux Rolling" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2556.054 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "140412_KB" -context "xsim\\usage"
webtalk_transmit -clientid 261796892 -regid "" -xml /media/root/New Volume/IITD/4th/COL 216/Lab/A5/DataPath/DataPath.sim/sim_1/behav/xsim.dir/DC_behav/webtalk/usage_statistics_ext_xsim.xml -html /media/root/New Volume/IITD/4th/COL 216/Lab/A5/DataPath/DataPath.sim/sim_1/behav/xsim.dir/DC_behav/webtalk/usage_statistics_ext_xsim.html -wdm /media/root/New Volume/IITD/4th/COL 216/Lab/A5/DataPath/DataPath.sim/sim_1/behav/xsim.dir/DC_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
